/**
 * ============================================================================
 * ATOMIC DESIGN COMPONENT LIBRARY
 * ============================================================================
 *
 * Organization follows Brad Frost's Atomic Design methodology:
 * Atoms → Molecules → Organisms → Templates → Pages
 *
 * Generated by Uma (UX Design Expert) - AIOS
 * @see https://atomicdesign.bradfrost.com/
 */

// =============================================================================
// ATOMS - Basic building blocks
// =============================================================================
// Atoms are the smallest possible components, such as buttons, inputs, labels.
// They can't be broken down any further without ceasing to be functional.

export { Button, buttonVariants } from './ui/button';
export { Input } from './ui/input';
export { Textarea } from './ui/textarea';
export { Label } from './ui/label';
export { Switch } from './ui/switch';
export { Slider } from './ui/slider';
export { Separator } from './ui/separator';
export { Avatar, AvatarImage, AvatarFallback } from './ui/avatar';

// =============================================================================
// MOLECULES - Simple combinations of atoms
// =============================================================================
// Molecules are relatively simple groups of UI elements functioning together.
// Example: A form label + input field = form-field molecule

export {
  Select,
  SelectContent,
  SelectGroup,
  SelectItem,
  SelectLabel,
  SelectSeparator,
  SelectTrigger,
  SelectValue,
} from './ui/select';

export {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from './ui/accordion';

export {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from './ui/dropdown-menu';

// =============================================================================
// ORGANISMS - Complex UI sections
// =============================================================================
// Organisms are relatively complex components composed of groups of molecules
// and/or atoms and/or other organisms.

export {
  Card,
  CardHeader,
  CardFooter,
  CardTitle,
  CardAction,
  CardDescription,
  CardContent,
} from './ui/card';

// Feature Components (Custom Organisms)
export { HookCard } from './hooks/hook-card';
export { HookList } from './hooks/hook-list';
export { SlidePreview } from './carousel/slide-preview';
export { IdeaForm } from './forms/idea-form';
export { Header } from './layout/header';

// =============================================================================
// COMPONENT REGISTRY
// =============================================================================
// Centralized registry for component metadata and documentation

export const COMPONENT_REGISTRY = {
  atoms: {
    Button: {
      name: 'Button',
      path: '@/components/ui/button',
      variants: ['default', 'destructive', 'outline', 'secondary', 'ghost', 'link'],
      sizes: ['default', 'xs', 'sm', 'lg', 'icon', 'icon-xs', 'icon-sm', 'icon-lg'],
      a11y: ['keyboard-nav', 'focus-visible', 'aria-disabled'],
    },
    Input: {
      name: 'Input',
      path: '@/components/ui/input',
      a11y: ['aria-invalid', 'focus-visible', 'disabled-state'],
    },
    Textarea: {
      name: 'Textarea',
      path: '@/components/ui/textarea',
      a11y: ['aria-invalid', 'focus-visible', 'disabled-state'],
    },
    Label: {
      name: 'Label',
      path: '@/components/ui/label',
      a11y: ['htmlFor-association'],
    },
    Switch: {
      name: 'Switch',
      path: '@/components/ui/switch',
      sizes: ['default', 'sm'],
      a11y: ['keyboard-nav', 'focus-visible', 'aria-checked'],
    },
    Slider: {
      name: 'Slider',
      path: '@/components/ui/slider',
      a11y: ['keyboard-nav', 'focus-visible', 'aria-valuenow'],
    },
    Separator: {
      name: 'Separator',
      path: '@/components/ui/separator',
      a11y: ['decorative-role'],
    },
    Avatar: {
      name: 'Avatar',
      path: '@/components/ui/avatar',
      a11y: ['alt-text', 'fallback'],
    },
  },
  molecules: {
    Select: {
      name: 'Select',
      path: '@/components/ui/select',
      sizes: ['default', 'sm'],
      a11y: ['keyboard-nav', 'focus-visible', 'aria-expanded'],
    },
    Accordion: {
      name: 'Accordion',
      path: '@/components/ui/accordion',
      a11y: ['keyboard-nav', 'aria-expanded', 'aria-controls'],
    },
    DropdownMenu: {
      name: 'DropdownMenu',
      path: '@/components/ui/dropdown-menu',
      a11y: ['keyboard-nav', 'focus-trap', 'aria-expanded'],
    },
  },
  organisms: {
    Card: {
      name: 'Card',
      path: '@/components/ui/card',
      subcomponents: ['CardHeader', 'CardFooter', 'CardTitle', 'CardAction', 'CardDescription', 'CardContent'],
    },
    HookCard: {
      name: 'HookCard',
      path: '@/components/hooks/hook-card',
      description: 'Displays a selectable hook option',
    },
    HookList: {
      name: 'HookList',
      path: '@/components/hooks/hook-list',
      description: 'List of hook cards for selection',
    },
    SlidePreview: {
      name: 'SlidePreview',
      path: '@/components/carousel/slide-preview',
      description: 'Twitter-style carousel slide preview with editing',
    },
    IdeaForm: {
      name: 'IdeaForm',
      path: '@/components/forms/idea-form',
      description: 'Main form for carousel idea input',
    },
    Header: {
      name: 'Header',
      path: '@/components/layout/header',
      description: 'App header with navigation and user menu',
    },
  },
} as const;

// =============================================================================
// TYPE EXPORTS
// =============================================================================

export type ComponentCategory = keyof typeof COMPONENT_REGISTRY;
export type AtomName = keyof typeof COMPONENT_REGISTRY.atoms;
export type MoleculeName = keyof typeof COMPONENT_REGISTRY.molecules;
export type OrganismName = keyof typeof COMPONENT_REGISTRY.organisms;
